### ISSUE TITLE
Error when compiling plugin

### ISSUE THREAD

**Issue by JulienMaille** [smallcloudai/refact-vs-classic#11]
I have cloned and opened the `RefactExtension.sln` solution with Visual Studio 2022.
When compiling in `Debug | Any CPU` I end up with following error message:
`1>C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\amd64\Microsoft.Common.CurrentVersion.targets(5229,5): error MSB3030: Could not copy the file "D:\Dev\refact-vs-classic\MultilineGreyText\Resources\refact-lsp.exe" because it was not found.
`
What did I do wrong?

**Comment by JulienMaille** [comment]
> Hi! You need build https://github.com/smallcloudai/refact-lsp and put artefact in right place

geez this is what I suspected. Is there a way to get the exe from github artifacts? I don't have the toolchain to compile Rust

**Comment by olegklimov** [comment]
@JulienMaille Sure, press Actions, there are downloadable artifacts. That's what I did for my windows box when I tested this plugin.
