### ISSUE TITLE
VS doesn't kill refact-lsp after close

### ISSUE THREAD

**Issue by reymondzzzz** [smallcloudai/refact-vs-classic#14]

**Comment by digital-phoenix** [comment]
@reymondzzzz is this after visual studio is closed or just one of the files or both?

**Comment by hazratisulton** [comment]
> @reymondzzzz is this after visual studio is closed or just one of the files or both?
After visual studio is closed.

**Comment by olegklimov** [comment]
It exits correctly if VS is shut down correctly.

It looks like refact-lsp stays open if it panics inside some of its rust internals.
