### ISSUE TITLE
Execution dies on Rpc.Invoke

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-vs-classic#21]
I added "AAA1" and "AAA2" around the call, only "AAA1" is visible in the logs.

On the screenshot is my attempt to reproduce this again, right after merging #10 .

Windows 11
Debug build from source
`refact-lsp` downloaded from https://github.com/smallcloudai/refact-lsp/actions/runs/7289748072
dist-x86_64-pc-windows-msvc

![IMAGE 2023-12-26 20:49:40](https://github.com/smallcloudai/refact-vs-classic/assets/18546213/85d98807-9ec7-4eb5-b783-0cfba0837c14)

**Comment by olegklimov** [comment]
@digital-phoenix that's a blocker for any other testing at this point :/

Kirill @reymondzzzz might help you, but he doesn't have windows either, only a virtual machine that's not ideal for debugging things like that one.

**Comment by digital-phoenix** [comment]
@would it be possible to upload the output window data as an external file? Also if you comment out line 150 "info.CreateNoWindow = true;" in RefactLanguageClient.cs do you see a server window pop up at all?

**Comment by reymondzzzz** [comment]
Guys, I found commit in lsp binary. This commit broke rpc requests. I will try to fix it ASAP

**Comment by reymondzzzz** [comment]
So after 6 hours debug I found reason why it doesn't work. For completion we need text of file and we save it in cache in rust with didOpen/didChanged events. Your code did completion before this events(another ide did event and after call completion). And rust throws exception and rust fall down with panic before and your code restarts rust and call didChange event. After works ok. Oleg found bug with blocked http server. This bug in rust which lsp started in main thread and blocked http server startup. I moved lsp in another thread. It works. So.... My bugfix didn't restart lsp thread and another events doesn't work because thread has panic. 

What we need to do:
-  You need rework code with right order of event didChange/didOpen -> completion
-  I need to fix lsp panic with exception. Thread will restart never with any exception.

**Comment by digital-phoenix** [comment]
@reymondzzzz I believe the latest pull request solves the problem

**Comment by reymondzzzz** [comment]
this? #22  You add only stderr-log in args of rust? how it helps?

**Comment by digital-phoenix** [comment]
@reymondzzzz when I tested it without that addition the rpc call would hang indefinitely and with the code added the rpc call worked correctly.

**Comment by digital-phoenix** [comment]
@reymondzzzz if you still see have the issue even with the pull request let me know what file type you're testing with.

**Comment by reymondzzzz** [comment]
It still doesn't work. 
```
// main.cpp

#include <stdio.h>
#include <stdlib.h>


int ma

```
I try to complete main

**Comment by digital-phoenix** [comment]
Can you see if a c# file works better?

**Comment by reymondzzzz** [comment]
same
```
using System;

namespace HelloWorld
{
    class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine
```

**Comment by reymondzzzz** [comment]
How `--logs-stderr` helps? it's only redirect stderr in stdout.

**Comment by reymondzzzz** [comment]
@digital-phoenix take this pr https://github.com/smallcloudai/refact-lsp/pull/55 for lsp. It fixes this problem, but log has errors. Fix pls event order bug. 
<img width="1162" alt="image" src="https://github.com/smallcloudai/refact-vs-classic/assets/15812493/eb946f6a-33da-448b-961f-60ddf50ac488">

**Comment by digital-phoenix** [comment]
@reymondzzzz I couldn't reproduce the issue you're seeing but I resolved some potentially related issues.

**Comment by reymondzzzz** [comment]
Check events. Order is broken. Fix it pls

**Comment by olegklimov** [comment]
🎉  🎉  🎉  we're moving forward 🎉  🎉  🎉

**Comment by digital-phoenix** [comment]
@reymondzzzz the order of events is correct. This is accomplished in one of two ways. Either the lsp will recognize the extension of a file type and the lsp server will automatically launch. Then the visual studio sdk will handle the server messages automatically. Failing an automatic launch the lsp server will be manually launched and every time the lsp is asked for a completion the code will first check to see if the lsp knows about the file. If it doesn't it will send a didOpen message to the server and create a change handler that will send updates to the lsp whenever the file changes. 

Can you make sure to update to your code with the latest pull request and send a file containing all the info from the output window and another file containing all the server output?

**Comment by digital-phoenix** [comment]
@reymondzzzz let me know if the server still receives getCompletion calls with the latest pull request

**Comment by reymondzzzz** [comment]
I will try it now.

**Comment by reymondzzzz** [comment]
@digital-phoenix with last commits it works correct. Great job!

**Comment by olegklimov** [comment]
OK, it still dies, but less often. It looks like rust doesn't validate inputs very well, and panics again (hypothesis, need to check).

The current problem for this issue is this: the exception between AAA1 and AAA2 doesn't get caught by "catch (Exception)" and doesn't go to the status bar. Maybe there's some kind of a more wide exception, like BaseException in python?

There are two things to fix:
* panic
* show error to user

Panic we'll fix elsewhere, but the lack of an error message is what makes this issue much worse -- it looks like it works, but it doesn't.

To reproduce error: start writing new code at the end of any file => lsp will die very soon.
