### ISSUE TITLE
IDE crashes if trying completion when cursor is on a string with space in front of it

### ISSUE THREAD

**Issue by hazratisulton** [smallcloudai/refact-vs-classic#26]
**Steps to reproduce:**
Add at least one space character on line
Try completion from start of line

**Expected result:**
IDE and completion working

**Actual result:**
After entering several characters and space character IDE crashes
https://github.com/smallcloudai/refact-vs-classic/assets/140423660/f86eb6a4-937d-410e-a573-61923159de30

**Software versions:**
Microsoft Visual Studio Community 2022 (64-bit) - Current Version 17.8.4
Refact plugin v 0.0.1 https://github.com/smallcloudai/refact-vs-classic/actions/runs/7469728225?pr=22
Windows 11 Pro 22H2 22621.2861

**Logs:**
[rustbinary.zip](https://github.com/smallcloudai/refact-vs-classic/files/13947110/rustbinary.zip)
[ActivityLog.zip](https://github.com/smallcloudai/refact-vs-classic/files/13947113/ActivityLog.zip)

**Comment by digital-phoenix** [comment]
Why is the server running in it's own window in your setup?

**Comment by digital-phoenix** [comment]
Make sure to uninstall any previous versions when installing the latest one because it doesn't look like you are running the correct version.  The most up to date version would show a status bar icon and not have the server running in a separate window.

**Comment by hazratisulton** [comment]
Server isn't running separately. I just opened logs (.\.cache\refact\logs\rustbinary.2024-01-17) of refact-lsp server built into the plugin.
Uninstalled plugin, then installed plugin from https://github.com/smallcloudai/refact-vs-classic/actions/runs/7469728225.
https://github.com/smallcloudai/refact-vs-classic/assets/140423660/fec0eede-4e7a-496a-af02-4e61006aef44

**Comment by digital-phoenix** [comment]
Looks like spaces isn't the trigger. Can you try typing one letter at a time and waiting for the completion before typing the next letter and see if it still crashes?

**Comment by hazratisulton** [comment]
Space - crash:
https://github.com/smallcloudai/refact-vs-classic/assets/140423660/44153bbe-8373-4005-9552-370ef9b9fef2
Letter - no crash:
https://github.com/smallcloudai/refact-vs-classic/assets/140423660/9f6ac686-577c-451e-ba03-41a00213d1d6

**Comment by digital-phoenix** [comment]
What do you mean by space because your letter example includes spaces?

**Comment by hazratisulton** [comment]
Try to reproduce this steps for IDE crash:
Create new file
Type a space character
Return to the beginning of the line
Type any characters, for example "def"
Type a space character
Wait for the fall
(If necessary, try typing one letter at a time and wait)

**Comment by digital-phoenix** [comment]
This should be fixed in the latest pull request

**Comment by hazratisulton** [comment]
Tested plugin from https://github.com/smallcloudai/refact-vs-classic/actions/runs/7563144505
Looks like previous case not reproducing now. But there is crash after Enter:
https://github.com/smallcloudai/refact-vs-classic/assets/140423660/6a450bd9-6b27-40b2-a7df-85f9de5cbb55

**Comment by digital-phoenix** [comment]
@hazratisulton are you on the company slack because I would like to communicate with you more broadly beyond this specific issue.

**Comment by digital-phoenix** [comment]
@hazratisulton this should be fixed now

**Comment by hazratisulton** [comment]
Both cases fixed in this version https://github.com/smallcloudai/refact-vs-classic/actions/runs/7588140824
