### ISSUE TITLE
Grey text doesn't appear, then appears after backspace-space

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-vs-classic#5]
![IMAGE 2023-11-20 09:59:22](https://github.com/smallcloudai/refact-vs-classic/assets/18546213/4469b956-0e16-4349-9487-e839236ece1f)

Easy to reproduce, happens often

**Comment by digital-phoenix** [comment]
Can you describe the issue here?

**Comment by olegklimov** [comment]
Grey text doesn't appear at all, but it gets saved in cache. If you hit Backspace, and then Space, you'll see quick completion coming from cache. Easy to reproduce -- happens a lot.

**Comment by digital-phoenix** [comment]
how do you know it is getting saved in cache?

**Comment by digital-phoenix** [comment]
but what makes you think that it is not just the original answer arriving slowly instead of a cached response?

**Comment by olegklimov** [comment]
Because originally you can wait as much as you want, the grey text will not appear.

**Comment by hazratisulton** [comment]
Checked plugin version 0.0.2 from marketplace - problem is no longer reproducible.
