### ISSUE TITLE
Completion -- when not exactly at the end of the line

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-vs-classic#6]
Cursor is not at the end of the line, but behind some special characters (regex) like closing parenthesis: "def f(x: stri|):", completion should give "ng):" and replace the rest or the string.

<img width="282" alt="image" src="https://github.com/smallcloudai/refact-vs-classic/assets/18546213/25ea0e07-e9ff-4713-bf97-832f04c9ace4">

From VS Code the regex is:

let right_of_cursor_has_only_special_chars = Boolean(right_of_cursor.match(/^[:\s\t\n\r(){},."'\];]*$/));

The other keyword is "multiline=False", the model switches to a special mode to replace the rest of the current string.

**Comment by sakshambp** [comment]
What is expected behaviour? Is it to retain the special characters such as `)` while replacing string?

**Comment by olegklimov** [comment]
> retain the special characters such as ) while replacing string

Right, it does this by relying on the model -- that it will produce all the characters needed. The plugin need to replace the rest of the current string with the model output.

**Comment by sakshambp** [comment]
Can you please provide me steps on how do i setup local dev environment? I can work on this

**Comment by olegklimov** [comment]
Oh awesome that you want to check it out!

I can't reproduce the exact steps I followed to install it on my Windows box, but I remember it was easy.

Something like:

* Install Visual Studio
* `git clone` the repo
* Open it in VS
* Agree to download a plugin development SDK of some sort
=> You can run and debug it by pressing F5

If you want to try this, you can record your actions and write it down to CONTRIBUTING.md -- that would we fantastic.

**Comment by digital-phoenix** [comment]
@sakshambp this may not be the best issue to work on as it requires a major refactor to get the plugin to insert grey  text in between  the text in the document.

**Comment by olegklimov** [comment]
It almost works, renders it wrong a bit. Should be a small fix.

![IMAGE 2024-01-02 23:42:46](https://github.com/smallcloudai/refact-vs-classic/assets/18546213/dba5ac78-370c-4a98-9a1f-9eec20777b97)

^^ on the screenshot: shows `);` in black not quite at the right place, shows "AlignCenter" correctly.

**Comment by hazratisulton** [comment]
Checked plugin version 0.0.2 from marketplace - problem is no longer reproducible.
