### ISSUE TITLE
[VS Classic] Distinguish multiline and single line completions

### ISSUE THREAD

**Issue by olegklimov** [smallcloudai/refact-vs-classic#9]
<b>Multi line</b> completion -- should happen when the cursor is on a empty string, or on a string with only spaces.

A typical example of multi line completion:

```
def do_this_thing():
    |
```

User hits Enter, IDE provides auto-indent, and then a function body should appear as grey text.

To implement it, the plugin should check if the line is empty or it has only spaces, then delete all the spaces on the empty line (in memory, not in the editor), and then request the model for completions.

It's important to delete spaces before asking the model, because there should be a way for the model to suggest code with less indent. Typical example of this:

```
int main()
{
    printf("Hello world!\n");
    |
```

Now the completion is "}", but it will not work unless there are no spaces on that line. With spaces, the model is constrained to "&nbsp;&nbsp;&nbsp;&nbsp;}".

Now the <b>single line</b> completion should happen when the current line is not empty, and there is nothing except closing special characters on the right:

```
let right_of_cursor_has_only_special_chars = Boolean(right_of_cursor.match(/^[:\s\t\n\r(){},."'];]*$/));
```

If `multiline=false`, the model will return only the remainder of the current line, and stop. The plugin needs to replace the line ending in the editor with the new completion given by the model.

If the cursor is not exactly on the last character of the current line, then #6  about how to deal with that case.

**Comment by olegklimov** [comment]
Current behavior:

* Hitting Enter doesn't request any completions at all
* `multiline` is always true, in completion request in RefactLanguageClient.cs

**Comment by digital-phoenix** [comment]
@olegklimov Currently the the lsp server returns completion suggestions by providing the text that should go after the current cursor position. If you want the completion to replace white space the code should use a different endpoint for the completions.  If the lsp server supported textDocument/inlineCompletion from the latest spec that could be used instead which would provide the information needed to replace white space on the current line.

**Comment by digital-phoenix** [comment]
@olegklimov just to clarify if the cursor is at the end of the line it should use the multi line version. Is that right?

**Comment by olegklimov** [comment]
No, if the cursor line is empty => multiline (this happens often when you hit Enter)
Iight_of_cursor_has_only_special_chars  => single line
else => ignore

**Comment by olegklimov** [comment]
This works.

There are still problems with overlapping characters but that one works.
